import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartContext } from "@/app/context/cartContext";
import { CartProvider } from "@/app/context/cartContext";
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon: '/assets/G.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
          <Navbar />
          
          <CartProvider>
            <main className="flex-grow">
            {children}
            </main>
          </CartProvider>

          <Footer />
      </body>
    </html>
  );
}
